import { useCallback, useEffect, useState } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import {
  getPluginById, getPluginChangelogById, getPluginConfigById, getPluginReadmeById,
  installPluginFromUrl, listPluginMarket, listPluginPagesById, listPlugins,
  reloadPluginById, setPluginEnabledById, uninstallPluginById, updatePluginConfigById, updatePlugins,
} from '@/api/openapi';
import { Markdown } from '@/components/content/Markdown';
import { MonacoEditor } from '@/components/editor/MonacoEditor';
import { Dialog, DialogClose } from '@/components/headless/Dialog';
import { confirmAction, toast } from '@/stores/feedback';
import { errorMessage, JsonObject, objectList, parseJsonObject, prettyJson, recordId, responseData } from '@/routes/configuration/model';

function pluginId(item: JsonObject) { return recordId(item, 'name', 'id', 'plugin_id', 'module_name'); }
function pluginTitle(item: JsonObject) { return String(item.display_name || item.name || item.id || 'Plugin'); }

export default function ExtensionPage() {
  const { pluginId: routePluginId } = useParams(); const location = useLocation();
  if (routePluginId) return <PluginDetail pluginId={routePluginId} />;
  return location.pathname === '/extension-marketplace' ? <PluginMarket /> : <InstalledPlugins />;
}

function PageHeader({ children, description, title }: { children?: React.ReactNode; description: string; title: string }) {
  return <header className="monitor-header"><div><h1>{title}</h1><p>{description}</p></div><div className="monitor-actions">{children}</div></header>;
}

function InstalledPlugins() {
  const [items, setItems] = useState<JsonObject[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(objectList(responseData(await listPlugins({ query: { include_reserved: true } })), ['plugins', 'items'])); } catch (cause) { setError(errorMessage(cause, 'Failed to load plugins.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const toggle = async (item: JsonObject) => { const id = pluginId(item); if (!id) return; try { await setPluginEnabledById({ body: { plugin_id: id, enabled: !(item.activated ?? item.enabled ?? true) } }); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to update plugin.')); } };
  const remove = async (item: JsonObject) => { const id = pluginId(item); if (!id || !await confirmAction({ danger: true, title: 'Uninstall plugin', message: `Uninstall ${pluginTitle(item)}?` })) return; try { await uninstallPluginById({ query: { plugin_id: id }, body: { delete_config: false, delete_data: false } }); toast.success('Plugin uninstalled.'); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to uninstall plugin.')); } };
  const visible = items.filter((item) => `${pluginTitle(item)} ${pluginId(item)} ${item.author || ''}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="monitor-page extension-page"><PageHeader description="Manage installed plugins and their runtime state." title="Extensions"><Link to="/extension-marketplace">Marketplace</Link><button disabled={loading} onClick={() => void load()} type="button">Refresh</button></PageHeader><div className="data-filters"><input onChange={(event) => setSearch(event.target.value)} placeholder="Search plugins" value={search} /></div>{error && <div className="monitor-error">{error}</div>}{loading && <div className="monitor-loading">Loading…</div>}<div className="extension-grid">{visible.map((item, index) => { const id = pluginId(item) || `plugin-${index}`; const enabled = (item.activated ?? item.enabled) !== false; return <article className="route-card extension-card" key={id}><div><h2>{pluginTitle(item)}</h2><p>{String(item.desc || item.description || '')}</p></div><small>{id} · {String(item.version || '—')} · {String(item.author || '—')}</small><label className="config-toggle"><input checked={enabled} onChange={() => void toggle(item)} type="checkbox" /> Enabled</label><div className="monitor-actions"><Link to={`/extension/${encodeURIComponent(id)}`}>Details</Link>{!item.reserved && <button className="button--danger" onClick={() => void remove(item)} type="button">Uninstall</button>}</div></article>; })}</div>{!loading && !visible.length && <div className="monitor-empty">No plugins found.</div>}</div>;
}

function PluginMarket() {
  const [items, setItems] = useState<JsonObject[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [keyword, setKeyword] = useState(''); const [installing, setInstalling] = useState(''); const [url, setUrl] = useState('');
  const load = useCallback(async (refresh = false) => { setLoading(true); setError(''); try { setItems(objectList(responseData(await listPluginMarket({ query: { force_refresh: refresh, keyword: keyword.trim() || undefined, page: 1, page_size: 100 } })), ['items', 'plugins', 'data'])); } catch (cause) { setError(errorMessage(cause, 'Failed to load marketplace.')); } finally { setLoading(false); } }, [keyword]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);
  const install = async (item?: JsonObject) => { const target = item ? String(item.download_url || item.repo_url || item.url || item.repository || '') : url.trim(); if (!target) { toast.warning('A plugin URL is required.'); return; } const id = item ? pluginId(item) || target : target; setInstalling(id); try { await installPluginFromUrl({ body: { url: target, download_url: typeof item?.download_url === 'string' ? item.download_url : undefined } }); toast.success('Plugin installed.'); setUrl(''); } catch (cause) { toast.error(errorMessage(cause, 'Failed to install plugin.')); } finally { setInstalling(''); } };
  return <div className="monitor-page extension-page"><PageHeader description="Discover plugins or install one from a URL." title="Plugin marketplace"><Link to="/extension">Installed</Link><button disabled={loading} onClick={() => void load(true)} type="button">Refresh catalog</button></PageHeader><div className="route-card extension-install"><input onChange={(event) => setUrl(event.target.value)} placeholder="Plugin repository or package URL" value={url} /><button disabled={!url.trim() || Boolean(installing)} onClick={() => void install()} type="button">Install URL</button></div><div className="data-filters"><input onChange={(event) => setKeyword(event.target.value)} placeholder="Search marketplace" value={keyword} /></div>{error && <div className="monitor-error">{error}</div>}<div className="extension-grid">{items.map((item, index) => { const id = pluginId(item) || `market-${index}`; return <article className="route-card extension-card" key={id}><div><h2>{pluginTitle(item)}</h2><p>{String(item.desc || item.description || '')}</p></div><small>{String(item.author || '—')} · ★ {String(item.stars || 0)} · {String(item.category || 'other')}</small><button disabled={installing === id} onClick={() => void install(item)} type="button">{installing === id ? 'Installing…' : 'Install'}</button></article>; })}</div>{!loading && !items.length && <div className="monitor-empty">No marketplace results.</div>}</div>;
}

function PluginDetail({ pluginId: id }: { pluginId: string }) {
  const navigate = useNavigate(); const [plugin, setPlugin] = useState<JsonObject>({}); const [pages, setPages] = useState<JsonObject[]>([]); const [config, setConfig] = useState('{}'); const [savedConfig, setSavedConfig] = useState('{}'); const [readme, setReadme] = useState(''); const [changelog, setChangelog] = useState(''); const [tab, setTab] = useState('overview'); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [detailResponse, configResponse, pageResponse] = await Promise.all([getPluginById({ query: { plugin_id: id } }), getPluginConfigById({ query: { plugin_id: id } }).catch(() => null), listPluginPagesById({ query: { plugin_id: id } }).catch(() => null)]); setPlugin(responseData<JsonObject>(detailResponse) ?? {}); const configData = responseData<JsonObject>(configResponse); const text = prettyJson(configData?.config ?? configData ?? {}); setConfig(text); setSavedConfig(text); setPages(objectList(responseData(pageResponse), ['pages', 'items'])); } catch (cause) { setError(errorMessage(cause, 'Failed to load plugin.')); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (tab === 'readme' && !readme) void getPluginReadmeById({ query: { plugin_id: id } }).then((response) => setReadme(String(responseData(response) ?? ''))).catch((cause) => toast.error(errorMessage(cause, 'Failed to load README.'))); if (tab === 'changelog' && !changelog) void getPluginChangelogById({ query: { plugin_id: id } }).then((response) => setChangelog(String(responseData(response) ?? ''))).catch((cause) => toast.error(errorMessage(cause, 'Failed to load changelog.'))); }, [changelog, id, readme, tab]);
  const save = async () => { let value: JsonObject; try { value = parseJsonObject(config); } catch (cause) { toast.error(errorMessage(cause, 'Invalid JSON.')); return; } setSaving(true); try { await updatePluginConfigById({ body: { plugin_id: id, config: value } }); setSavedConfig(prettyJson(value)); toast.success('Plugin configuration saved.'); } catch (cause) { toast.error(errorMessage(cause, 'Failed to save configuration.')); } finally { setSaving(false); } };
  const reload = async () => { try { await reloadPluginById({ body: { plugin_id: id } }); toast.success('Plugin reloaded.'); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to reload plugin.')); } };
  const update = async () => { try { await updatePlugins({ body: { plugin_id: id } }); toast.success('Plugin update started.'); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to update plugin.')); } };
  const remove = async () => { if (!await confirmAction({ danger: true, title: 'Uninstall plugin', message: `Uninstall ${pluginTitle(plugin)}?` })) return; try { await uninstallPluginById({ query: { plugin_id: id } }); toast.success('Plugin uninstalled.'); navigate('/extension'); } catch (cause) { toast.error(errorMessage(cause, 'Failed to uninstall plugin.')); } };
  return <div className="monitor-page extension-page"><PageHeader description={`${id} · ${String(plugin.version || '—')}`} title={pluginTitle(plugin)}><Link to="/extension">Back</Link><button onClick={() => void reload()} type="button">Reload</button><button onClick={() => void update()} type="button">Update</button>{!plugin.reserved && <button className="button--danger" onClick={() => void remove()} type="button">Uninstall</button>}</PageHeader>{error && <div className="monitor-error">{error}</div>}{loading ? <div className="monitor-loading">Loading…</div> : <><nav className="config-tabs">{['overview', 'config', 'readme', 'changelog'].map((name) => <button aria-pressed={tab === name} key={name} onClick={() => setTab(name)} type="button">{name}</button>)}</nav>{tab === 'overview' && <section className="route-card plugin-overview"><p>{String(plugin.desc || plugin.description || 'No description.')}</p><dl><dt>Author</dt><dd>{String(plugin.author || '—')}</dd><dt>Repository</dt><dd>{String(plugin.repo || plugin.repo_url || '—')}</dd></dl>{pages.length > 0 && <div><h2>Plugin pages</h2><div className="monitor-actions">{pages.map((page, index) => { const name = recordId(page, 'name', 'page_name', 'id') || `page-${index}`; return <Link key={name} to={`/plugin-page/${encodeURIComponent(id)}/${encodeURIComponent(name)}`}>{String(page.title || page.display_name || name)}</Link>; })}</div></div>}</section>}{tab === 'config' && <section className="route-card config-editor-panel config-editor-panel--settings"><MonacoEditor language="json" onChange={setConfig} value={config} /><div className="monitor-actions"><button disabled={config === savedConfig} onClick={() => setConfig(savedConfig)} type="button">Reset</button><button className="button--primary" disabled={saving || config === savedConfig} onClick={() => void save()} type="button">Save</button></div></section>}{tab === 'readme' && <section className="route-card markdown-panel"><Markdown content={readme || 'Loading…'} /></section>}{tab === 'changelog' && <section className="route-card markdown-panel"><Markdown content={changelog || 'Loading…'} /></section>}</>}</div>;
}
