import { useCallback, useEffect, useRef, useState, type ChangeEvent } from 'react';
import {
  createMcpServer, deleteMcpServer, deleteSkillByName, listCommandConflicts, listCommands,
  listMcpServers, listSkills, listTools, setMcpServerEnabled, setToolEnabled, setToolPermission,
  testMcpServer, updateCommand, updateMcpServer, updateSkillByName, uploadSkillsBatch,
} from '@/api/openapi';
import { MdiIcon } from '@/components/icons/MdiIcon';
import { confirmAction, toast } from '@/stores/feedback';
import { errorMessage, type JsonObject, objectList, parseJsonObject, prettyJson, recordId, responseData } from '@/routes/configuration/model';
import { JsonConfigDialog } from '@/routes/configuration/ConfigurationUi';
import { useTranslation } from 'react-i18next';

function SectionState({ error, loading }: { error: string; loading: boolean }) {
  if (loading) return <div className="extension-state"><MdiIcon className="mdi-spin" name="mdi-loading" /></div>;
  if (error) return <div className="monitor-error">{error}</div>;
  return null;
}

export function ComponentsSection() {
  const { t } = useTranslation(); const e = (key: string) => t(`features.extension.${key}`);
  const [commands, setCommands] = useState<JsonObject[]>([]); const [tools, setTools] = useState<JsonObject[]>([]); const [conflicts, setConflicts] = useState<JsonObject[]>([]);
  const [tab, setTab] = useState<'commands' | 'tools'>('commands'); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [commandResponse, toolResponse, conflictResponse] = await Promise.all([listCommands(), listTools(), listCommandConflicts().catch(() => null)]); setCommands(objectList(responseData(commandResponse), ['commands', 'items', 'data'])); setTools(objectList(responseData(toolResponse), ['tools', 'items', 'data'])); setConflicts(objectList(responseData(conflictResponse), ['conflicts', 'items', 'data'])); } catch (cause) { setError(errorMessage(cause, e('messages.operationFailed'))); } finally { setLoading(false); } }, [t]);
  useEffect(() => { void load(); }, [load]);
  const toggleCommand = async (item: JsonObject) => { const id = recordId(item, 'handler_full_name', 'command_id', 'id', 'name'); if (!id) return; try { await updateCommand({ path: { command_id: id }, body: { enabled: item.enabled === false } }); await load(); } catch (cause) { toast.error(errorMessage(cause, e('messages.operationFailed'))); } };
  const updateAlias = async (item: JsonObject, alias: string) => { const id = recordId(item, 'handler_full_name', 'command_id', 'id', 'name'); if (!id || alias === String(item.alias || '')) return; try { await updateCommand({ path: { command_id: id }, body: { alias } }); toast.success(e('messages.saveSuccess')); await load(); } catch (cause) { toast.error(errorMessage(cause, e('messages.operationFailed'))); } };
  const toggleTool = async (item: JsonObject) => { const id = recordId(item, 'name', 'tool_id', 'id'); if (!id) return; try { await setToolEnabled({ path: { tool_id: id }, body: { enabled: item.enabled === false } }); await load(); } catch (cause) { toast.error(errorMessage(cause, e('messages.operationFailed'))); } };
  const permission = async (item: JsonObject, value: 'admin' | 'member') => { const id = recordId(item, 'name', 'tool_id', 'id'); if (!id) return; try { await setToolPermission({ path: { tool_id: id }, body: { permission: value } }); await load(); } catch (cause) { toast.error(errorMessage(cause, e('messages.operationFailed'))); } };
  const rows = (tab === 'commands' ? commands : tools).filter((item) => JSON.stringify(item).toLowerCase().includes(search.toLowerCase()));
  return <section className="extension-section"><header className="extension-section__header"><div><h2>{e('tabs.handlersOperation')}</h2><p>{e('subtitle')}</p></div><button onClick={() => void load()} type="button"><MdiIcon name="mdi-refresh" />{e('buttons.refresh')}</button></header><div className="extension-controls"><nav className="extension-subtabs"><button aria-pressed={tab === 'commands'} onClick={() => setTab('commands')} type="button">{e('detail.handlerGroups.commands')}</button><button aria-pressed={tab === 'tools'} onClick={() => setTab('tools')} type="button">{e('detail.handlerGroups.functionTools')}</button></nav><input onChange={(event) => setSearch(event.target.value)} placeholder={e('search.placeholder')} value={search} /></div>{conflicts.length > 0 && <div className="extension-warning"><MdiIcon name="mdi-alert-outline" />{conflicts.length} command conflicts</div>}<SectionState error={error} loading={loading} />{!loading && <div className="extension-table-wrap"><table className="extension-table"><thead><tr><th>{e('table.headers.name')}</th><th>{e('table.headers.description')}</th><th>{e('table.headers.status')}</th><th>{e('table.headers.actions')}</th></tr></thead><tbody>{rows.map((item, index) => { const id = recordId(item, tab === 'commands' ? 'handler_full_name' : 'name', 'id', 'command_id', 'tool_id') || `${tab}-${index}`; return <tr key={id}><td><strong>{String(item.display_name || item.name || item.command || id)}</strong><small>{String(item.origin_name || item.origin || '')}</small></td><td>{String(item.description || item.desc || '—')}</td><td><label className="config-toggle"><input checked={item.enabled !== false} onChange={() => void (tab === 'commands' ? toggleCommand(item) : toggleTool(item))} type="checkbox" />{item.enabled === false ? e('status.disabled') : e('status.enabled')}</label></td><td>{tab === 'commands' ? <input className="extension-alias" defaultValue={String(item.alias || '')} onBlur={(event) => void updateAlias(item, event.target.value)} placeholder="Alias" /> : <select onChange={(event) => void permission(item, event.target.value as 'admin' | 'member')} value={String(item.permission || 'member')}><option value="member">Member</option><option value="admin">Admin</option></select>}</td></tr>; })}</tbody></table>{!rows.length && <div className="monitor-empty">{e('empty.noPlugins')}</div>}</div>}</section>;
}

export function McpSection() {
  const { t } = useTranslation(); const e = (key: string) => t(`features.extension.${key}`); const m = (key: string) => t(`features.tooluse.${key}`);
  const [items, setItems] = useState<JsonObject[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState<JsonObject | null>(null); const [source, setSource] = useState('{}'); const [saving, setSaving] = useState(false); const [testing, setTesting] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(objectList(responseData(await listMcpServers()), ['servers', 'items', 'data'])); } catch (cause) { setError(errorMessage(cause, e('messages.operationFailed'))); } finally { setLoading(false); } }, [t]);
  useEffect(() => { void load(); }, [load]);
  const open = (item?: JsonObject) => { setEditing(item ?? {}); setSource(prettyJson(item ?? { name: '', enabled: true, transport: 'stdio', command: '', args: [] })); };
  const save = async () => { let config: JsonObject; try { config = parseJsonObject(source); } catch (cause) { toast.error(errorMessage(cause, 'Invalid JSON')); return; } const oldName = recordId(editing ?? {}, 'name', 'server_name'); const name = recordId(config, 'name', 'server_name'); if (!name) { toast.warning('Server name is required'); return; } setSaving(true); try { if (oldName) await updateMcpServer({ path: { server_name: oldName }, body: { ...config, name } }); else await createMcpServer({ body: { ...config, name } }); toast.success(e('messages.saveSuccess')); setEditing(null); await load(); } catch (cause) { toast.error(errorMessage(cause, e('messages.operationFailed'))); } finally { setSaving(false); } };
  const toggle = async (item: JsonObject) => { const name = recordId(item, 'name', 'server_name'); try { await setMcpServerEnabled({ path: { server_name: name }, body: { enabled: item.enabled === false } }); await load(); } catch (cause) { toast.error(errorMessage(cause, e('messages.operationFailed'))); } };
  const test = async (item: JsonObject) => { const name = recordId(item, 'name', 'server_name'); setTesting(name); try { await testMcpServer({ path: { server_name: name } }); toast.success(e('messages.pluginValidateSuccess')); } catch (cause) { toast.error(errorMessage(cause, e('messages.operationFailed'))); } finally { setTesting(''); } };
  const remove = async (item: JsonObject) => { const name = recordId(item, 'name', 'server_name'); if (!name || !await confirmAction({ danger: true, title: e('buttons.deleteSource'), message: name })) return; try { await deleteMcpServer({ path: { server_name: name } }); toast.success(e('messages.deleteSuccess')); await load(); } catch (cause) { toast.error(errorMessage(cause, e('messages.operationFailed'))); } };
  return <section className="extension-section"><header className="extension-section__header"><div><h2>{e('tabs.installedMcpServers')}</h2><p>{m('mcpServers.description')}</p></div><div><button onClick={() => void load()} type="button"><MdiIcon name="mdi-refresh" />{e('buttons.refresh')}</button><button className="button--primary" onClick={() => open()} type="button"><MdiIcon name="mdi-plus" />{e('buttons.install')}</button></div></header><SectionState error={error} loading={loading} /><div className="extension-card-grid">{items.map((item, index) => { const name = recordId(item, 'name', 'server_name') || `server-${index}`; return <article className="extension-resource-card" key={name}><header><MdiIcon name="mdi-server" /><div><h3>{name}</h3><p>{String(item.transport || 'stdio')} · {String(item.url || item.command || '—')}</p></div><label className="config-toggle"><input checked={item.enabled !== false} onChange={() => void toggle(item)} type="checkbox" /></label></header><div><button disabled={testing === name} onClick={() => void test(item)} type="button">{testing === name ? '…' : 'Test'}</button><button onClick={() => open(item)} type="button">{e('buttons.configure')}</button><button className="button--danger" onClick={() => void remove(item)} type="button">{e('buttons.uninstall')}</button></div></article>; })}</div>{!loading && !items.length && <div className="monitor-empty">{e('empty.noPlugins')}</div>}<JsonConfigDialog busy={saving} initialMode="json" onChange={setSource} onOpenChange={(openValue) => !openValue && setEditing(null)} onSave={() => void save()} open={editing !== null} title={editing && recordId(editing, 'name', 'server_name') ? e('buttons.configure') : e('buttons.install')} value={source} /></section>;
}

export function SkillsSection() {
  const { t } = useTranslation(); const e = (key: string, options?: Record<string, unknown>) => t(`features.extension.${key}`, options);
  const input = useRef<HTMLInputElement>(null); const [items, setItems] = useState<JsonObject[]>([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(objectList(responseData(await listSkills()), ['skills', 'items', 'data'])); } catch (cause) { setError(errorMessage(cause, e('messages.operationFailed'))); } finally { setLoading(false); } }, [t]);
  useEffect(() => { void load(); }, [load]);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files || []); event.target.value = ''; if (!files.length) return; setUploading(true); try { await uploadSkillsBatch({ body: { files } }); toast.success(e('skills.batchResultSummary', { total: files.length, success: files.length })); await load(); } catch (cause) { toast.error(errorMessage(cause, e('messages.operationFailed'))); } finally { setUploading(false); } };
  const toggle = async (item: JsonObject) => { const name = recordId(item, 'name', 'skill_name', 'id'); try { await updateSkillByName({ body: { skill_name: name, enabled: item.enabled === false, active: item.enabled === false } }); await load(); } catch (cause) { toast.error(errorMessage(cause, e('messages.operationFailed'))); } };
  const remove = async (item: JsonObject) => { const name = recordId(item, 'name', 'skill_name', 'id'); if (!name || !await confirmAction({ danger: true, title: e('buttons.uninstall'), message: name })) return; try { await deleteSkillByName({ query: { skill_name: name } }); toast.success(e('messages.deleteSuccess')); await load(); } catch (cause) { toast.error(errorMessage(cause, e('messages.operationFailed'))); } };
  return <section className="extension-section"><header className="extension-section__header"><div><h2>{e('tabs.skills')}</h2><p>{e('skills.runtimeHint')}</p></div><div><button onClick={() => void load()} type="button"><MdiIcon name="mdi-refresh" />{e('skills.refresh')}</button><input accept=".zip,application/zip" hidden multiple onChange={(event) => void upload(event)} ref={input} type="file" /><button className="button--primary" disabled={uploading} onClick={() => input.current?.click()} type="button"><MdiIcon name="mdi-upload" />{uploading ? e('skills.uploading') : e('skills.upload')}</button></div></header><SectionState error={error} loading={loading} /><div className="extension-card-grid">{items.map((item, index) => { const name = recordId(item, 'name', 'skill_name', 'id') || `skill-${index}`; return <article className="extension-resource-card" key={name}><header><MdiIcon name="mdi-lightning-bolt" /><div><h3>{String(item.display_name || name)}</h3><p>{String(item.description || item.source || '')}</p></div><label className="config-toggle"><input checked={(item.enabled ?? item.active) !== false} onChange={() => void toggle(item)} type="checkbox" /></label></header><div><button className="button--danger" onClick={() => void remove(item)} type="button">{e('buttons.uninstall')}</button></div></article>; })}</div>{!loading && !items.length && <div className="monitor-empty"><h3>{e('skills.empty')}</h3><p>{e('skills.emptyHint')}</p></div>}</section>;
}
