import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams } from 'react-router-dom';
import { getPluginById, getPluginPageById, openApiAxiosClient } from '@/api/openapi';
import { errorMessage, JsonObject, responseData } from '@/routes/configuration/model';

const CHANNEL = 'astrbot-plugin-page';
export function validPluginEndpoint(value: unknown) {
  if (typeof value !== 'string') throw new Error('Plugin endpoint must be a string.');
  const parts = value.trim().replace(/^\/+/, '').split('/');
  if (!parts.length || parts.some((part) => !part || part === '.' || part === '..' || part.includes('\\') || part.includes('?') || part.includes('#'))) throw new Error('Invalid plugin endpoint.');
  return parts.map(encodeURIComponent).join('/');
}

export default function PluginPage() {
  const { pluginName = '', pageName = '' } = useParams(); const frame = useRef<HTMLIFrameElement>(null); const [plugin, setPlugin] = useState<JsonObject>({}); const [page, setPage] = useState<JsonObject>({}); const [src, setSrc] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const post = useCallback((payload: JsonObject) => frame.current?.contentWindow?.postMessage({ channel: CHANNEL, ...payload }, '*'), []);
  const sendContext = useCallback(() => post({ kind: 'context', context: { pluginName, displayName: plugin.display_name || plugin.name || pluginName, pageName, pageTitle: page.title || page.display_name || pageName, locale: localStorage.getItem('astrbot-locale') || 'zh-CN', i18n: plugin.i18n || {}, isDark: document.documentElement.dataset.theme === 'dark' } }), [page, pageName, plugin, pluginName, post]);
  useEffect(() => { let active = true; setLoading(true); Promise.all([getPluginById({ query: { plugin_id: pluginName } }), getPluginPageById({ query: { plugin_id: pluginName, page_name: pageName } })]).then(([pluginResponse, pageResponse]) => { if (!active) return; const pluginData = responseData<JsonObject>(pluginResponse) ?? {}; const entry = responseData<JsonObject | string>(pageResponse); const pageData = typeof entry === 'string' ? { content_path: entry } : entry ?? {}; const path = pageData.content_path; if (typeof path !== 'string' || !path) throw new Error('Plugin page entry was not found.'); const url = new URL(path, window.location.origin); url.searchParams.set('theme', document.documentElement.dataset.theme === 'dark' ? 'dark' : 'light'); setPlugin(pluginData); setPage(pageData); setSrc(`${url.pathname}${url.search}${url.hash}`); }).catch((cause) => active && setError(errorMessage(cause, 'Failed to load plugin page.'))).finally(() => active && setLoading(false)); return () => { active = false; }; }, [pageName, pluginName]);
  useEffect(() => { const listener = (event: MessageEvent) => { if (event.source !== frame.current?.contentWindow) return; const message = event.data as JsonObject; if (!message || message.channel !== CHANNEL) return; if (message.kind === 'ready') { sendContext(); return; } if (message.kind !== 'request' || typeof message.requestId !== 'string') return; const respond = (ok: boolean, value: unknown) => post({ kind: 'response', requestId: message.requestId, ok, ...(ok ? { data: value } : { error: value }) }); void (async () => { try { const endpoint = validPluginEndpoint(message.endpoint); const url = `/api/v1/plugins/extensions/${encodeURIComponent(pluginName)}/${endpoint}`; const method = String(message.action || '').split(':')[1]; if (!['get', 'post', 'put', 'patch', 'delete'].includes(method)) throw new Error(`Unsupported plugin bridge action: ${String(message.action)}`); const result = await openApiAxiosClient.request({ method, url, params: message.params as JsonObject | undefined, data: message.body }); respond(true, (result.data as { data?: unknown })?.data ?? result.data); } catch (cause) { respond(false, errorMessage(cause, 'Plugin bridge request failed.')); } })(); }; window.addEventListener('message', listener); window.addEventListener('astrbot-locale-changed', sendContext); return () => { window.removeEventListener('message', listener); window.removeEventListener('astrbot-locale-changed', sendContext); }; }, [pluginName, post, sendContext]);
  if (loading) return <div className="plugin-page-state">Loading plugin page…</div>;
  if (error) return <div className="plugin-page-state monitor-error">{error}</div>;
  return <iframe className="plugin-page-frame" onLoad={sendContext} ref={frame} referrerPolicy="no-referrer" sandbox="allow-scripts allow-forms allow-downloads" src={src} title={`${pluginName}: ${pageName}`} />;
}
