import { useCallback, useEffect, useState } from 'react';
import { createConfigProfile, deleteConfigProfile, getConfigProfile, listConfigProfiles, updateConfigProfileContent } from '@/api/openapi';
import { MonacoEditor } from '@/components/editor/MonacoEditor';
import { confirmAction, toast } from '@/stores/feedback';
import { ConfigPageShell, LoadingState } from './ConfigurationUi';
import { errorMessage, JsonObject, objectList, parseJsonObject, prettyJson, recordId, responseData } from './model';

type Profile = JsonObject & { conf_id?: string; id?: string; name?: string };
export default function ConfigPage() {
  const [profiles, setProfiles] = useState<Profile[]>([]); const [selected, setSelected] = useState('default'); const [source, setSource] = useState('{}'); const [saved, setSaved] = useState('{}');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [newName, setNewName] = useState('');
  const loadProfiles = useCallback(async () => { const data = responseData(await listConfigProfiles()); setProfiles(objectList(data, ['info_list', 'configs', 'profiles']) as Profile[]); }, []);
  const loadContent = useCallback(async (id: string) => { setLoading(true); setError(''); try { const data = responseData<JsonObject>(await getConfigProfile({ path: { config_id: id } })); const text = prettyJson(data?.config ?? data); setSource(text); setSaved(text); } catch (cause) { setError(errorMessage(cause, 'Failed to load configuration.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void loadProfiles().catch((cause) => setError(errorMessage(cause, 'Failed to load profiles.'))); }, [loadProfiles]);
  useEffect(() => { void loadContent(selected); }, [loadContent, selected]);
  const save = async () => { let config: JsonObject; try { config = parseJsonObject(source); } catch (cause) { toast.error(errorMessage(cause, 'Invalid JSON.')); return; } setSaving(true); try { await updateConfigProfileContent({ path: { config_id: selected }, body: config }); setSaved(prettyJson(config)); toast.success('Configuration saved.'); } catch (cause) { toast.error(errorMessage(cause, 'Failed to save configuration.')); } finally { setSaving(false); } };
  const create = async () => { if (!newName.trim()) return; try { const data = responseData<JsonObject>(await createConfigProfile({ body: { name: newName.trim(), config: {} } })); await loadProfiles(); setNewName(''); setSelected(recordId(data, 'conf_id', 'id') || 'default'); toast.success('Configuration profile created.'); } catch (cause) { toast.error(errorMessage(cause, 'Failed to create profile.')); } };
  const remove = async () => { if (selected === 'default' || !await confirmAction({ danger: true, title: 'Delete profile', message: `Delete configuration profile ${selected}?` })) return; try { await deleteConfigProfile({ path: { config_id: selected } }); setSelected('default'); await loadProfiles(); toast.success('Profile deleted.'); } catch (cause) { toast.error(errorMessage(cause, 'Failed to delete profile.')); } };
  return <ConfigPageShell actions={<><button disabled={loading || source === saved} onClick={() => setSource(saved)} type="button">Reset</button><button className="button--primary" disabled={loading || saving || source === saved} onClick={() => void save()} type="button">{saving ? 'Saving…' : 'Save'}</button></>} description="Edit the default configuration or manage reusable configuration profiles." title="Configuration">
    <div className="config-workspace"><aside className="route-card config-profile-list">{profiles.map((profile, index) => { const id = recordId(profile, 'conf_id', 'id') || `profile-${index}`; return <button className={selected === id ? 'is-active' : ''} key={id} onClick={() => setSelected(id)} type="button">{String(profile.name || id)}</button>; })}<div className="config-inline-form"><input onChange={(event) => setNewName(event.target.value)} placeholder="New profile name" value={newName} /><button disabled={!newName.trim()} onClick={() => void create()} type="button">Add</button></div>{selected !== 'default' && <button className="button--danger" onClick={() => void remove()} type="button">Delete selected</button>}</aside><section className="route-card config-editor-panel"><LoadingState error={error} loading={loading} />{!loading && <MonacoEditor ariaLabel="Configuration JSON" language="json" onChange={setSource} value={source} />}</section></div>
  </ConfigPageShell>;
}
