import { useCallback, useEffect, useState } from 'react';
import { createCronJob, deleteCronJob, listCronJobs, runCronJob, updateCronJob } from '@/api/openapi';
import { confirmAction, toast } from '@/stores/feedback';
import { ConfigPageShell, JsonConfigDialog, LoadingState } from './ConfigurationUi';
import { errorMessage, JsonObject, objectList, parseJsonObject, prettyJson, recordId, responseData } from './model';

export default function CronPage() {
  const [items, setItems] = useState<JsonObject[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState<JsonObject | null>(null); const [source, setSource] = useState('{}'); const [saving, setSaving] = useState(false); const [running, setRunning] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(objectList(responseData(await listCronJobs()), ['jobs', 'cron_jobs', 'items'])); } catch (cause) { setError(errorMessage(cause, 'Failed to load scheduled jobs.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const open = (item: JsonObject | null) => { setEditing(item ?? {}); const copy = { ...(item ?? { name: '', cron_expression: '0 * * * *', timezone: 'UTC', enabled: true, payload: {} }) }; delete copy.job_id; setSource(prettyJson(copy)); };
  const save = async () => { let config: JsonObject; try { config = parseJsonObject(source); } catch (cause) { toast.error(errorMessage(cause, 'Invalid JSON.')); return; } const id = recordId(editing ?? {}, 'job_id', 'id'); if (!config.name || (!config.cron_expression && !config.run_at)) { toast.warning('name and cron_expression or run_at are required.'); return; } setSaving(true); try { if (id) await updateCronJob({ path: { job_id: id }, body: config }); else await createCronJob({ body: config }); toast.success('Scheduled job saved.'); setEditing(null); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to save scheduled job.')); } finally { setSaving(false); } };
  const patchEnabled = async (item: JsonObject) => { const id = recordId(item, 'job_id', 'id'); if (!id) return; try { await updateCronJob({ path: { job_id: id }, body: { enabled: item.enabled === false } }); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to update job.')); } };
  const run = async (item: JsonObject) => { const id = recordId(item, 'job_id', 'id'); if (!id) return; setRunning(id); try { await runCronJob({ path: { job_id: id } }); toast.success('Job started.'); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to run job.')); } finally { setRunning(''); } };
  const remove = async (item: JsonObject) => { const id = recordId(item, 'job_id', 'id'); if (!id || !await confirmAction({ danger: true, title: 'Delete scheduled job', message: `Delete ${String(item.name || id)}?` })) return; try { await deleteCronJob({ path: { job_id: id } }); toast.success('Scheduled job deleted.'); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to delete job.')); } };
  return <ConfigPageShell actions={<><button onClick={() => open(null)} type="button">Add job</button><button disabled={loading} onClick={() => void load()} type="button">Refresh</button></>} description="Create recurring or one-time tasks and run them on demand." title="Scheduled jobs"><LoadingState error={error} loading={loading} /><div className="monitor-table-wrap route-card"><table className="monitor-table"><thead><tr><th>Name</th><th>Schedule</th><th>Target</th><th>Status</th><th /></tr></thead><tbody>{items.map((item, index) => { const id = recordId(item, 'job_id', 'id') || `job-${index}`; return <tr key={id}><td><strong>{String(item.name || id)}</strong><small>{String(item.note || item.description || '')}</small></td><td>{String(item.run_at || item.cron_expression || '—')}<small>{String(item.timezone || '')}</small></td><td>{String(item.session || item.persona_id || '—')}</td><td><label className="config-toggle"><input checked={item.enabled !== false} onChange={() => void patchEnabled(item)} type="checkbox" />{item.enabled === false ? 'Disabled' : 'Enabled'}</label></td><td><button disabled={running === id} onClick={() => void run(item)} type="button">{running === id ? 'Running…' : 'Run'}</button><button onClick={() => open(item)} type="button">Edit</button><button className="button--danger" onClick={() => void remove(item)} type="button">Delete</button></td></tr>; })}</tbody></table>{!loading && !items.length && <div className="monitor-empty">No scheduled jobs.</div>}</div><JsonConfigDialog busy={saving} onChange={setSource} onOpenChange={(value) => !value && setEditing(null)} onSave={() => void save()} open={editing !== null} title={recordId(editing ?? {}, 'job_id', 'id') ? 'Edit job' : 'Add job'} value={source} /></ConfigPageShell>;
}
