import { useCallback, useEffect, useState } from 'react';
import { createPersona, deletePersonaById, listPersonas, updatePersonaById } from '@/api/openapi';
import { confirmAction, toast } from '@/stores/feedback';
import { ConfigPageShell, JsonConfigDialog, LoadingState } from './ConfigurationUi';
import { errorMessage, JsonObject, objectList, parseJsonObject, prettyJson, recordId, responseData } from './model';

export default function PersonaPage() {
  const [items, setItems] = useState<JsonObject[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [filter, setFilter] = useState('');
  const [editing, setEditing] = useState<JsonObject | null>(null); const [source, setSource] = useState('{}'); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(objectList(responseData(await listPersonas()), ['personas', 'items'])); } catch (cause) { setError(errorMessage(cause, 'Failed to load personas.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const open = (item: JsonObject | null) => { setEditing(item ?? {}); setSource(prettyJson(item ?? { persona_id: '', system_prompt: '', begin_dialogs: [], tools: [], skills: [] })); };
  const save = async () => { let config: JsonObject; try { config = parseJsonObject(source); } catch (cause) { toast.error(errorMessage(cause, 'Invalid JSON.')); return; } const oldId = recordId(editing ?? {}, 'persona_id', 'id'); const id = recordId(config, 'persona_id', 'id'); const prompt = config.system_prompt; if (!id || typeof prompt !== 'string') { toast.warning('persona_id and system_prompt are required.'); return; } setSaving(true); try { if (oldId) await updatePersonaById({ body: { ...config, persona_id: oldId } }); else await createPersona({ body: { ...config, persona_id: id, system_prompt: prompt } }); toast.success('Persona saved.'); setEditing(null); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to save persona.')); } finally { setSaving(false); } };
  const remove = async (item: JsonObject) => { const id = recordId(item, 'persona_id', 'id'); if (!id || !await confirmAction({ danger: true, title: 'Delete persona', message: `Delete ${id}?` })) return; try { await deletePersonaById({ query: { persona_id: id } }); toast.success('Persona deleted.'); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to delete persona.')); } };
  const visible = items.filter((item) => recordId(item, 'persona_id', 'id').toLowerCase().includes(filter.toLowerCase()));
  return <ConfigPageShell actions={<><input aria-label="Search personas" onChange={(event) => setFilter(event.target.value)} placeholder="Search" value={filter} /><button onClick={() => open(null)} type="button">Add persona</button><button disabled={loading} onClick={() => void load()} type="button">Refresh</button></>} description="Manage reusable system prompts, tools, skills and opening dialogs." title="Personas"><LoadingState error={error} loading={loading} /><div className="config-card-grid">{visible.map((item, index) => { const id = recordId(item, 'persona_id', 'id') || `persona-${index}`; return <article className="route-card config-record config-record--persona" key={id}><div><h2>{String(item.name || id)}</h2><p>{String(item.description || item.system_prompt || '').slice(0, 140)}</p></div><div className="monitor-actions"><button onClick={() => open(item)} type="button">Edit</button><button className="button--danger" onClick={() => void remove(item)} type="button">Delete</button></div></article>; })}</div>{!loading && !visible.length && <div className="monitor-empty">No persona found.</div>}<JsonConfigDialog busy={saving} onChange={setSource} onOpenChange={(value) => !value && setEditing(null)} onSave={() => void save()} open={editing !== null} title={recordId(editing ?? {}, 'persona_id', 'id') ? 'Edit persona' : 'Add persona'} value={source} /></ConfigPageShell>;
}
