import { useCallback, useEffect, useState } from 'react';
import { createProvider, deleteProviderById, listProviders, setProviderEnabledById, testProviderById, updateProviderById } from '@/api/openapi';
import { confirmAction, toast } from '@/stores/feedback';
import { ConfigPageShell, JsonConfigDialog, LoadingState } from './ConfigurationUi';
import { errorMessage, JsonObject, objectList, parseJsonObject, prettyJson, recordId, responseData } from './model';

export default function ProviderPage() {
  const [items, setItems] = useState<JsonObject[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [editing, setEditing] = useState<JsonObject | null>(null); const [source, setSource] = useState('{}'); const [saving, setSaving] = useState(false); const [testing, setTesting] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(objectList(responseData(await listProviders()), ['providers', 'data'])); } catch (cause) { setError(errorMessage(cause, 'Failed to load providers.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const open = (item: JsonObject | null) => { setEditing(item ?? {}); setSource(prettyJson(item ?? { id: '', provider: '', enable: true })); };
  const save = async () => { let config: JsonObject; try { config = parseJsonObject(source); } catch (cause) { toast.error(errorMessage(cause, 'Invalid JSON.')); return; } const id = recordId(editing ?? {}, 'id', 'provider_id'); setSaving(true); try { if (id) await updateProviderById({ body: { provider_id: id, config } }); else await createProvider({ body: { config } }); toast.success('Provider saved.'); setEditing(null); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to save provider.')); } finally { setSaving(false); } };
  const toggle = async (item: JsonObject) => { const id = recordId(item, 'id', 'provider_id'); if (!id) return; try { await setProviderEnabledById({ body: { provider_id: id, enabled: !(item.enable ?? item.enabled ?? true) } }); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to update provider.')); } };
  const remove = async (item: JsonObject) => { const id = recordId(item, 'id', 'provider_id'); if (!id || !await confirmAction({ danger: true, title: 'Delete provider', message: `Delete ${id}?` })) return; try { await deleteProviderById({ query: { provider_id: id } }); toast.success('Provider deleted.'); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to delete provider.')); } };
  const test = async (item: JsonObject) => { const id = recordId(item, 'id', 'provider_id'); if (!id) return; setTesting(id); try { await testProviderById({ body: { provider_id: id } }); toast.success(`${id} is available.`); } catch (cause) { toast.error(errorMessage(cause, 'Provider test failed.')); } finally { setTesting(''); } };
  return <ConfigPageShell actions={<><button onClick={() => open(null)} type="button">Add provider</button><button disabled={loading} onClick={() => void load()} type="button">Refresh</button></>} description="Configure model providers, availability and capabilities." title="Providers"><LoadingState error={error} loading={loading} />
    <div className="config-card-grid">{items.map((item, index) => { const id = recordId(item, 'id', 'provider_id') || `provider-${index}`; const enabled = (item.enable ?? item.enabled) !== false; return <article className="route-card config-record" key={id}><div><h2>{String(item.name || id)}</h2><p>{String(item.provider || item.provider_type || item.capability || 'provider')}</p></div><label className="config-toggle"><input checked={enabled} onChange={() => void toggle(item)} type="checkbox" /> Enabled</label><div className="monitor-actions"><button disabled={testing === id} onClick={() => void test(item)} type="button">{testing === id ? 'Testing…' : 'Test'}</button><button onClick={() => open(item)} type="button">Edit</button><button className="button--danger" onClick={() => void remove(item)} type="button">Delete</button></div></article>; })}</div>{!loading && !items.length && <div className="monitor-empty">No provider configured.</div>}
    <JsonConfigDialog busy={saving} onChange={setSource} onOpenChange={(value) => !value && setEditing(null)} onSave={() => void save()} open={editing !== null} title={recordId(editing ?? {}, 'id', 'provider_id') ? 'Edit provider' : 'Add provider'} value={source} />
  </ConfigPageShell>;
}
