import { useCallback, useEffect, useState } from 'react';
import { createApiKey, deleteApiKey, getSystemConfig, listApiKeys, updateSystemConfig } from '@/api/openapi';
import { MonacoEditor } from '@/components/editor/MonacoEditor';
import { confirmAction, toast } from '@/stores/feedback';
import { ConfigPageShell, LoadingState } from './ConfigurationUi';
import { errorMessage, JsonObject, objectList, parseJsonObject, prettyJson, recordId, responseData } from './model';

export default function SettingsPage() {
  const [tab, setTab] = useState(() => window.location.hash.includes('openapi') ? 'openapi' : 'system'); const [source, setSource] = useState('{}'); const [saved, setSaved] = useState('{}');
  const [keys, setKeys] = useState<JsonObject[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [keyName, setKeyName] = useState(''); const [createdKey, setCreatedKey] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [configResponse, keyResponse] = await Promise.all([getSystemConfig(), listApiKeys().catch(() => null)]); const config = responseData<JsonObject>(configResponse); const text = prettyJson(config?.config ?? config); setSource(text); setSaved(text); setKeys(objectList(responseData(keyResponse), ['keys', 'api_keys', 'items'])); } catch (cause) { setError(errorMessage(cause, 'Failed to load settings.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const save = async () => { let config: JsonObject; try { config = parseJsonObject(source); } catch (cause) { toast.error(errorMessage(cause, 'Invalid JSON.')); return; } setSaving(true); try { await updateSystemConfig({ body: config }); setSaved(prettyJson(config)); toast.success('System settings saved.'); } catch (cause) { toast.error(errorMessage(cause, 'Failed to save settings.')); } finally { setSaving(false); } };
  const addKey = async () => { if (!keyName.trim()) return; try { const data = responseData<JsonObject>(await createApiKey({ body: { name: keyName.trim() } })); const secret = data?.key ?? data?.api_key ?? data?.token; setCreatedKey(typeof secret === 'string' ? secret : ''); setKeyName(''); toast.success('API key created.'); await load(); setTab('openapi'); } catch (cause) { toast.error(errorMessage(cause, 'Failed to create API key.')); } };
  const removeKey = async (item: JsonObject) => { const id = recordId(item, 'key_id', 'id'); if (!id || !await confirmAction({ danger: true, title: 'Delete API key', message: `Delete ${String(item.name || id)}?` })) return; try { await deleteApiKey({ path: { key_id: id } }); toast.success('API key deleted.'); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to delete API key.')); } };
  return <ConfigPageShell actions={<button disabled={loading} onClick={() => void load()} type="button">Refresh</button>} description="Manage dashboard runtime settings, security and OpenAPI credentials." title="Settings"><nav className="config-tabs"><button aria-pressed={tab === 'system'} onClick={() => setTab('system')} type="button">System configuration</button><button aria-pressed={tab === 'openapi'} onClick={() => setTab('openapi')} type="button">OpenAPI keys</button></nav><LoadingState error={error} loading={loading} />
    {!loading && tab === 'system' && <section className="route-card config-editor-panel config-editor-panel--settings"><MonacoEditor ariaLabel="System settings JSON" language="json" onChange={setSource} value={source} /><div className="monitor-actions"><button disabled={source === saved} onClick={() => setSource(saved)} type="button">Reset</button><button className="button--primary" disabled={saving || source === saved} onClick={() => void save()} type="button">{saving ? 'Saving…' : 'Save settings'}</button></div></section>}
    {!loading && tab === 'openapi' && <section className="route-card"><div className="monitor-toolbar"><div><h2>API keys</h2><p>New secrets are shown only after creation.</p></div><div className="config-inline-form"><input onChange={(event) => setKeyName(event.target.value)} placeholder="Key name" value={keyName} /><button disabled={!keyName.trim()} onClick={() => void addKey()} type="button">Create</button></div></div>{createdKey && <div className="config-secret" role="status"><strong>Copy this key now:</strong><code>{createdKey}</code><button onClick={() => void navigator.clipboard?.writeText(createdKey)} type="button">Copy</button></div>}<div className="monitor-table-wrap"><table className="monitor-table"><thead><tr><th>Name</th><th>Created</th><th>Expires</th><th /></tr></thead><tbody>{keys.map((item, index) => { const id = recordId(item, 'key_id', 'id') || `key-${index}`; return <tr key={id}><td>{String(item.name || id)}</td><td>{String(item.created_at || '—')}</td><td>{String(item.expires_at || '—')}</td><td><button className="button--danger" onClick={() => void removeKey(item)} type="button">Delete</button></td></tr>; })}</tbody></table>{!keys.length && <div className="monitor-empty">No API keys.</div>}</div></section>}
  </ConfigPageShell>;
}
