import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { deleteKnowledgeChunk, getKnowledgeDocument, listKnowledgeChunks } from '@/api/openapi';
import { Dialog, DialogClose } from '@/components/headless/Dialog';
import { confirmAction, toast } from '@/stores/feedback';
import { errorMessage, JsonObject, objectList, recordId, responseData } from '@/routes/configuration/model';

export default function DocumentDetailPage() {
  const { kbId = '', docId = '' } = useParams(); const [document, setDocument] = useState<JsonObject>({}); const [chunks, setChunks] = useState<JsonObject[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [total, setTotal] = useState(0); const [search, setSearch] = useState(''); const [selected, setSelected] = useState<JsonObject | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [docResponse, chunksResponse] = await Promise.all([getKnowledgeDocument({ path: { kb_id: kbId, document_id: docId } }), listKnowledgeChunks({ path: { kb_id: kbId }, query: { document_id: docId, page, page_size: pageSize } })]); const chunkData = responseData<JsonObject>(chunksResponse); setDocument(responseData<JsonObject>(docResponse) ?? {}); setChunks(objectList(chunkData, ['items', 'chunks'])); setTotal(typeof chunkData?.total === 'number' ? chunkData.total : objectList(chunkData, ['items']).length); } catch (cause) { setError(errorMessage(cause, 'Failed to load document.')); } finally { setLoading(false); } }, [docId, kbId, page, pageSize]);
  useEffect(() => { void load(); }, [load]);
  const remove = async (chunk: JsonObject) => { const id = recordId(chunk, 'chunk_id', 'id'); if (!id || !await confirmAction({ danger: true, title: 'Delete chunk', message: 'Delete this document chunk?' })) return; try { await deleteKnowledgeChunk({ path: { kb_id: kbId, chunk_id: id }, query: { document_id: docId } }); toast.success('Chunk deleted.'); await load(); } catch (cause) { toast.error(errorMessage(cause, 'Failed to delete chunk.')); } };
  const visible = useMemo(() => chunks.filter((chunk) => String(chunk.content || chunk.text || '').toLowerCase().includes(search.toLowerCase())), [chunks, search]);
  return <div className="monitor-page knowledge-page"><header className="monitor-header"><div><h1>{String(document.file_name || document.name || docId)}</h1><p>{String(document.file_type || document.type || 'Document')} · {String(document.file_size || document.size || '—')}</p></div><div className="monitor-actions"><Link to={`/knowledge-base/${encodeURIComponent(kbId)}`}>Back to knowledge base</Link><button disabled={loading} onClick={() => void load()} type="button">Refresh</button></div></header>{error && <div className="monitor-error">{error}</div>}<section className="route-card"><div className="monitor-toolbar"><div><h2>Document chunks</h2><p>{total} chunks</p></div><input onChange={(event) => setSearch(event.target.value)} placeholder="Filter current page" value={search} /></div><div className="monitor-table-wrap"><table className="monitor-table"><thead><tr><th>Index</th><th>Content</th><th>Characters</th><th /></tr></thead><tbody>{visible.map((chunk, index) => { const id = recordId(chunk, 'chunk_id', 'id') || `chunk-${index}`; const content = String(chunk.content || chunk.text || ''); return <tr key={id}><td>{String(chunk.chunk_index ?? index + 1)}</td><td className="knowledge-chunk-preview">{content.slice(0, 260)}</td><td>{String(chunk.char_count ?? content.length)}</td><td><button onClick={() => setSelected(chunk)} type="button">View</button><button className="button--danger" onClick={() => void remove(chunk)} type="button">Delete</button></td></tr>; })}</tbody></table>{!loading && !visible.length && <div className="monitor-empty">No chunks.</div>}</div><div className="pagination"><select onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1); }} value={pageSize}>{[10, 20, 50].map((size) => <option key={size}>{size}</option>)}</select><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} type="button">‹</button><span>{page}/{Math.max(1, Math.ceil(total / pageSize))}</span><button disabled={page * pageSize >= total} onClick={() => setPage((value) => value + 1)} type="button">›</button></div></section><Dialog onOpenChange={(open) => !open && setSelected(null)} open={Boolean(selected)} title={`Chunk ${String(selected?.chunk_index ?? '')}`}><pre className="knowledge-chunk-content">{String(selected?.content || selected?.text || '')}</pre><div className="dialog-actions"><DialogClose asChild><button type="button">Close</button></DialogClose></div></Dialog></div>;
}
